/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AdminRouteRouteImport } from './../routes/admin/route'
import { Route as EventDetailsRouteImport } from './../routes/event-details'
import { Route as FindRouteImport } from './../routes/find'
import { Route as LeaderboardRouteImport } from './../routes/leaderboard'
import { Route as RegisterRouteImport } from './../routes/register'
import { Route as ScannerRouteImport } from './../routes/scanner'
import { Route as SuccessRouteImport } from './../routes/success'
import { Route as AdminIndexRouteImport } from './../routes/admin/index'
import { Route as AdminRegisterRouteImport } from './../routes/admin/register'
import { Route as AdminRegistrationsRouteImport } from './../routes/admin/registrations'
import { Route as AdminScannerRouteImport } from './../routes/admin/scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailsRoute = EventDetailsRouteImport.update({
  id: '/event-details',
  path: '/event-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventDetailsRoute: typeof EventDetailsRoute
  FindRoute: typeof FindRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RegisterRoute: typeof RegisterRoute
  ScannerRoute: typeof ScannerRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-details': {
      id: '/event-details'
      path: '/event-details'
      fullPath: '/event-details'
      preLoaderRoute: typeof EventDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminRegisterRoute: AdminRegisterRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventDetailsRoute: EventDetailsRoute,
  FindRoute: FindRoute,
  LeaderboardRoute: LeaderboardRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.jsx'
import type { startInstance } from '../start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
