// REFERRAL DISABLED — Krishna names used to mint referral codes
export const KRISHNA_NAMES = [
  'Gopal', 'Govinda', 'Madhav', 'Murari', 'Kanha', 'Damodar', 'BankeBihari', 'Shyam',
  'Hari', 'Keshav', 'Narayan', 'Vasudev', 'Janardan', 'Madhava', 'RadheShyam', 'Giridhar',
  'Murlidhar', 'NandKishor', 'BalGopal', 'MakhanChor', 'YashodaNandan', 'Devakinandan',
  'Parthasarathi', 'Jagannath', 'Ranchhod', 'Vitthal', 'Pandurang', 'Srinath', 'Dwarkadhish',
  'RukminiPati', 'SatyabhamaPati', 'RadhaRamana', 'RadhaVallabh', 'Shyamsundar', 'Gokulanand',
  'VrindavanChandra', 'YaduNandan', 'Keshava', 'Hridan', 'Acyuta', 'Ananta', 'Achyuta',
  'Adhokshaja', 'Ajita', 'Amritaya', 'Aniruddha', 'Ari', 'Avyaya', 'Bhagavan', 'BhaktaVatsala',
  'Bhuvaneshvara', 'Brahma', 'Chakrapani', 'Chaturbhuja', 'Danavari', 'Dayanidhi', 'Deva',
  'Devesha', 'Dharanidhara', 'Dharma', 'Dharmadhyaksha', 'Dharmagupta', 'Dharmakrit',
  'Dharmapala', 'Dharmasetu', 'Dharmatma', 'Dhatri', 'Dhenunatha', 'Dhyanavasthita',
  'Dhyutidhara', 'Digambara', 'Dirghatama', 'Dirghayu', 'Dundubhi', 'Durga', 'Durjaya',
  'Durvasa', 'Dushyanta', 'Dvarakanatha', 'Dwaitatman', 'Ekadanta', 'Ekakshara', 'Ekanta',
  'Ekavira', 'Gajendra', 'Ganesha', 'Garuda', 'Gauranga', 'Girisha', 'Gopala', 'Gopinatha',
  'Gopta', 'Guru', 'Hamsa', 'Hanuman', 'Hara', 'Harikesha', 'Hiranyagarbha', 'Hiranyaksha',
  'Hiranyakashipu', 'Hrishikesha', 'Idhma', 'Indra', 'Ishana', 'Jagadisha', 'Jagadguru',
  'Jaladhi', 'Jaladhar', 'Jaladhara', 'Jaladhipati', 'Jaladhipa', 'Jaladhipati', 'Jaladhisha',
  'Jaladhipati', 'Jaladhipa', 'Jaladhisha', 'Jaladhipati', 'Jaladhipa', 'Jaladhisha',
];
