/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EventDetailsRouteImport } from './routes/event-details'
import { Route as FindRouteImport } from './routes/find'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAbhishekRouteImport } from './routes/admin/abhishek'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminFancyDressRouteImport } from './routes/admin/fancy-dress'
import { Route as AdminLadduGopalRouteImport } from './routes/admin/laddu-gopal'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminRegisterRouteImport } from './routes/admin/register'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminScannerRouteImport } from './routes/admin/scanner'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as AdminWhatsappRouteImport } from './routes/admin/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailsRoute = EventDetailsRouteImport.update({
  id: '/event-details',
  path: '/event-details',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAbhishekRoute = AdminAbhishekRouteImport.update({
  id: '/abhishek',
  path: '/abhishek',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFancyDressRoute = AdminFancyDressRouteImport.update({
  id: '/fancy-dress',
  path: '/fancy-dress',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLadduGopalRoute = AdminLadduGopalRouteImport.update({
  id: '/laddu-gopal',
  path: '/laddu-gopal',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/abhishek': typeof AdminAbhishekRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/fancy-dress': typeof AdminFancyDressRoute
  '/admin/laddu-gopal': typeof AdminLadduGopalRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/abhishek': typeof AdminAbhishekRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/fancy-dress': typeof AdminFancyDressRoute
  '/admin/laddu-gopal': typeof AdminLadduGopalRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/event-details': typeof EventDetailsRoute
  '/find': typeof FindRoute
  '/leaderboard': typeof LeaderboardRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/success': typeof SuccessRoute
  '/admin/abhishek': typeof AdminAbhishekRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/fancy-dress': typeof AdminFancyDressRoute
  '/admin/laddu-gopal': typeof AdminLadduGopalRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/register': typeof AdminRegisterRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/abhishek'
    | '/admin/admins'
    | '/admin/fancy-dress'
    | '/admin/laddu-gopal'
    | '/admin/leaderboard'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/admin/whatsapp'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/abhishek'
    | '/admin/admins'
    | '/admin/fancy-dress'
    | '/admin/laddu-gopal'
    | '/admin/leaderboard'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/admin/whatsapp'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/event-details'
    | '/find'
    | '/leaderboard'
    | '/register'
    | '/scanner'
    | '/success'
    | '/admin/abhishek'
    | '/admin/admins'
    | '/admin/fancy-dress'
    | '/admin/laddu-gopal'
    | '/admin/leaderboard'
    | '/admin/register'
    | '/admin/registrations'
    | '/admin/scanner'
    | '/admin/volunteers'
    | '/admin/whatsapp'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventDetailsRoute: typeof EventDetailsRoute
  FindRoute: typeof FindRoute
  LeaderboardRoute: typeof LeaderboardRoute
  RegisterRoute: typeof RegisterRoute
  ScannerRoute: typeof ScannerRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-details': {
      id: '/event-details'
      path: '/event-details'
      fullPath: '/event-details'
      preLoaderRoute: typeof EventDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/abhishek': {
      id: '/admin/abhishek'
      path: '/abhishek'
      fullPath: '/admin/abhishek'
      preLoaderRoute: typeof AdminAbhishekRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fancy-dress': {
      id: '/admin/fancy-dress'
      path: '/fancy-dress'
      fullPath: '/admin/fancy-dress'
      preLoaderRoute: typeof AdminFancyDressRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/laddu-gopal': {
      id: '/admin/laddu-gopal'
      path: '/laddu-gopal'
      fullPath: '/admin/laddu-gopal'
      preLoaderRoute: typeof AdminLadduGopalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/register': {
      id: '/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AdminRegisterRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAbhishekRoute: typeof AdminAbhishekRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminFancyDressRoute: typeof AdminFancyDressRoute
  AdminLadduGopalRoute: typeof AdminLadduGopalRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminRegisterRoute: typeof AdminRegisterRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAbhishekRoute: AdminAbhishekRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminFancyDressRoute: AdminFancyDressRoute,
  AdminLadduGopalRoute: AdminLadduGopalRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventDetailsRoute: EventDetailsRoute,
  FindRoute: FindRoute,
  LeaderboardRoute: LeaderboardRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
