/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as CompetitionsRouteImport } from './routes/competitions';
import { Route as EventDetailsRouteImport } from './routes/event-details';
import { Route as FindRouteImport } from './routes/find';
import { Route as LeaderboardRouteImport } from './routes/leaderboard';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ScannerRouteImport } from './routes/scanner';
import { Route as SuccessRouteImport } from './routes/success';
import { Route as AdminRouteRouteImport } from './routes/admin/route';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as AdminScannerRouteImport } from './routes/admin/scanner';
import { Route as AdminRegisterRouteImport } from './routes/admin/register';
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations';
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers';
import { Route as AdminAbhishekRouteImport } from './routes/admin/abhishek';
import { Route as AdminFancyDressRouteImport } from './routes/admin/fancy-dress';
import { Route as AdminLadduGopalRouteImport } from './routes/admin/laddu-gopal';
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard';
import { Route as AdminAdminsRouteImport } from './routes/admin/admins';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
});
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
});
const EventDetailsRoute = EventDetailsRouteImport.update({
  id: '/event-details',
  path: '/event-details',
  getParentRoute: () => rootRouteImport,
});
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
});
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
});
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
});
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
});
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
});
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
});
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AdminRouteRoute,
});
const AdminRegisterRoute = AdminRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AdminRouteRoute,
});
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
});
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRouteRoute,
});
const AdminAbhishekRoute = AdminAbhishekRouteImport.update({
  id: '/abhishek',
  path: '/abhishek',
  getParentRoute: () => AdminRouteRoute,
});
const AdminFancyDressRoute = AdminFancyDressRouteImport.update({
  id: '/fancy-dress',
  path: '/fancy-dress',
  getParentRoute: () => AdminRouteRoute,
});
const AdminLadduGopalRoute = AdminLadduGopalRouteImport.update({
  id: '/laddu-gopal',
  path: '/laddu-gopal',
  getParentRoute: () => AdminRouteRoute,
});
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRouteRoute,
});
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRouteRoute,
});

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren({
  AdminIndexRoute: AdminIndexRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminRegisterRoute: AdminRegisterRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminAbhishekRoute: AdminAbhishekRoute,
  AdminFancyDressRoute: AdminFancyDressRoute,
  AdminLadduGopalRoute: AdminLadduGopalRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminAdminsRoute: AdminAdminsRoute,
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  EventDetailsRoute: EventDetailsRoute,
  FindRoute: FindRoute,
  LeaderboardRoute: LeaderboardRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  SuccessRoute: SuccessRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
